function Update()
    FilePath = '..\\@Resources\\music.txt'
	FilePath = SKIN:MakePathAbsolute(FilePath)
    MeasureArtist = SKIN:GetMeasure('MeasureArtist')
    Artist = MeasureArtist:GetStringValue()
    MeasureTitle = SKIN:GetMeasure('MeasureTrack')
    Title = MeasureTitle:GetStringValue()
	MeasureState = SKIN:GetMeasure('MeasureState')
    State = MeasureState:GetStringValue()
	MeasurePosition = SKIN:GetMeasure('MeasurePosition')
    Position = MeasurePosition:GetStringValue()
	MeasureDuration = SKIN:GetMeasure('MeasureDuration')
    Duration = MeasureDuration:GetStringValue()
  
    OutputFile = io.open(FilePath, "w")
    OutputFile:write(Title .. ' - ' .. Artist .. '\n')
	OutputFile:write(State .. '\n')
	OutputFile:write(Position .. '\n')
	OutputFile:write(Duration .. '\n')
    OutputFile:close()
end